"""
Configuration constants for Hierarchical Market Model Streamlit app.
"""

# Default simulation parameters
DEFAULT_N_LEVELS = 4
DEFAULT_BRANCHING_FACTOR = 2
DEFAULT_LAMBDA_RATIO = 2.0
DEFAULT_FEEDBACK_STRENGTH = 0.05
DEFAULT_VOLATILITY = 0.01
DEFAULT_J_HORIZONTAL = 1.0
DEFAULT_J_VERTICAL = 2.0
DEFAULT_TEMPERATURE = 1.0

# Simulation settings
DEFAULT_N_STEPS = 1000
DEFAULT_BUBBLE_START = 200
DEFAULT_CRASH_TIME = 800

# Display settings
FIGURE_DPI = 100
GRID_FIGURE_SIZE = (8, 8)
TIME_SERIES_FIGURE_SIZE = (8, 10)

# Colors
COLOR_PRICE = '#3498db'
COLOR_MAGNETIZATION = '#9b59b6'
COLOR_BULLISH = '#2ecc71'
COLOR_BEARISH = '#e74c3c'
COLOR_DETECTED = '#27ae60'
COLOR_NOT_DETECTED = '#e67e22'

# LPPL thresholds
LPPL_CONFIDENCE_THRESHOLD = 0.85
LPPL_M_MIN = 0.1
LPPL_M_MAX = 0.9
LPPL_OMEGA_MIN = 5
LPPL_OMEGA_MAX = 15